# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: varchar
tagline: 'a stackdump of my mind'
description: 'a stackdump of my mind'
url: http://blog.prashu.com
baseurl: /

author:
  name: 'Prashanth K S'
  url: 'http://blog.prashu.com'           

paginate:         5

sidebar-links:
  dribbble: 
  email: 
  facebook: ksprashu
  flickr: ksprashu
  github: ksprashu
  instagram: ksprashu
  linkedin: ksprashu
  pinterest: ksprashu
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: geekoo
  stackoverflow: users/2603592/ksprashu

disqus: varchar
google_analytics: UA-56793220-1

gems:
  - jekyll-sitemap
  - jemoji
